;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        change-number-at-point
        delete-horizontal-space
        end-of-buffer
        f90-electric-insert
        kill-region-or-backward-word
        paredit-kill
        python-indent-electric-colon
        save-region-or-current-line
        smex
        sp--self-insert-command
        sp-remove-active-pair-overlay
        tagedit-insert-quote
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-mode
        f90-beginning-of-block
        f90-indent-new-line
        ido-find-file
        mouse-buffer-menu
        python-indent-dedent-line-backspace
        switch-window
        ))
